
project_id = "ctutwgntxhpuxtfkkdiy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[functions.create-merchant]
verify_jwt = false

[functions.issue-stamp]
verify_jwt = true

[functions.create-qr-code]
verify_jwt = true

[functions.redeem-reward]
verify_jwt = true
