
/**
 * Enum of all possible error types in the application
 */
export enum ErrorType {
  // Authentication errors
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_IN_USE = "AUTH_EMAIL_IN_USE",
  AUTH_EMAIL_NOT_CONFIRMED = "AUTH_EMAIL_NOT_CONFIRMED",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_MISSING_CREDENTIALS = "AUTH_MISSING_CREDENTIALS",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  
  // Validation errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  
  // Resource errors
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",
  
  // Permission errors
  PERMISSION_DENIED = "PERMISSION_DENIED",
  
  // Network errors
  NETWORK_ERROR = "NETWORK_ERROR",
  
  // Database errors
  DATABASE_ERROR = "DATABASE_ERROR",
  
  // Unknown/Generic errors
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  
  // Profile related errors
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED",
  
  // Merchant related errors
  MERCHANT_NOT_FOUND = "MERCHANT_NOT_FOUND",
  MERCHANT_UPDATE_FAILED = "MERCHANT_UPDATE_FAILED",
  
  // Stamp related errors
  STAMP_ISSUE_FAILED = "STAMP_ISSUE_FAILED",
  STAMP_REDEEM_FAILED = "STAMP_REDEEM_FAILED",
  
  // QR code related errors
  QR_CODE_INVALID = "QR_CODE_INVALID",
  QR_CODE_GENERATION_FAILED = "QR_CODE_GENERATION_FAILED",
  
  // Data operation errors
  DATA_FETCH_FAILED = "DATA_FETCH_FAILED",
  DATA_CREATE_FAILED = "DATA_CREATE_FAILED",
  DATA_UPDATE_FAILED = "DATA_UPDATE_FAILED",
  DATA_DELETE_FAILED = "DATA_DELETE_FAILED",
  
  // Offline operations errors
  OFFLINE_STORAGE_ERROR = "OFFLINE_STORAGE_ERROR",
  
  // Authorization errors
  UNAUTHORIZED = "UNAUTHORIZED"
}
