
/**
 * Enum for error types
 */
export enum ErrorType {
  // Authentication errors
  AUTH_EMAIL_NOT_CONFIRMED = 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_IN_USE = 'AUTH_EMAIL_IN_USE',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',
  AUTH_INVALID_RESET_TOKEN = 'AUTH_INVALID_RESET_TOKEN',
  AUTH_EMAIL_SEND_FAILED = 'AUTH_EMAIL_SEND_FAILED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_MISSING_EMAIL = 'AUTH_MISSING_EMAIL',
  AUTH_MISSING_PASSWORD = 'AUTH_MISSING_PASSWORD',
  AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
  
  // Stamp card errors
  STAMP_CARD_NOT_FOUND = 'STAMP_CARD_NOT_FOUND',
  STAMP_CARD_INACTIVE = 'STAMP_CARD_INACTIVE',
  STAMP_CARD_EXPIRED = 'STAMP_CARD_EXPIRED',
  STAMP_ISSUE_FAILED = 'STAMP_ISSUE_FAILED',
  STAMP_REDEEM_FAILED = 'STAMP_REDEEM_FAILED',
  STAMP_INSUFFICIENT = 'STAMP_INSUFFICIENT',
  
  // QR Code errors
  QR_CODE_INVALID = 'QR_CODE_INVALID',
  QR_CODE_EXPIRED = 'QR_CODE_EXPIRED',
  QR_CODE_USED = 'QR_CODE_USED',
  QR_CODE_GENERATION_FAILED = 'QR_CODE_GENERATION_FAILED',
  
  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  
  // Network/API errors
  NETWORK_ERROR = 'NETWORK_ERROR',
  API_ERROR = 'API_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  
  // Server errors
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  
  // Generic errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  
  // Offline-related errors
  OFFLINE_MODE = 'OFFLINE_MODE',
  OFFLINE_STORAGE_ERROR = 'OFFLINE_STORAGE_ERROR',
  OFFLINE_SYNC_FAILED = 'OFFLINE_SYNC_FAILED'
}

