// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asachfstvrtecrvxfqth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYWNoZnN0dnJ0ZWNydnhmcXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTQzOTYsImV4cCI6MjA1NjMzMDM5Nn0.5GyMztM-wEwglKDJct8xmhgZF5JF4Kdkyb0utS3RImg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);